# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/booksdb

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create

# Hibernate Search / OpenSearch
quarkus.hibernate-search-orm.elasticsearch.version=opensearch:2.19
quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=class:org.acme.config.SearchAnalysisConfigurer
quarkus.hibernate-search-orm.elasticsearch.hosts=localhost:9200
quarkus.hibernate-search-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy=sync

# Production overrides — point to docker-compose service names
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/booksdb
%prod.quarkus.hibernate-search-orm.elasticsearch.hosts=opensearch:9200
